PortfolioWebsite/Controllers/LoginController.cs
using PortfolioWebsite.BusinessLayer.Concrete;
using PortfolioWebsite.DataAccessLayer.Concrete;
using PortfolioWebsite.DataAccessLayer.EntityFramework;
using PortfolioWebsite.EntityLayer.Concrete;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PortfolioWebsite.Controllers
{
   
    public class LoginController : Controller
    {
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Index(Writer writer)
        {
            Context c = new Context();
            var datavalue = c.Writers.FirstOrDefault(x => x.WriterMail == writer.WriterMail && x.WriterPassword == writer.WriterPassword);
            if (datavalue != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,writer.WriterMail)
                };
                var useridentity = new ClaimsIdentity(claims, "key");
                ClaimsPrincipal principal = new ClaimsPrincipal(useridentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index", "Writer");
            }
            else
            {
                return View();
            }
        }
    }
}

//Context c = new Context();
//var datavalue = c.Writers.FirstOrDefault(x => x.Mail == writer.Mail && x.Password == writer.Password);
//if (datavalue != null)
//{
//    HttpContext.Session.SetString("username", writer.Mail);
//    return RedirectToAction("Index", "Writer");
//}
//else
//{
//    return View();
//}

PortfolioWebsite/Controllers/RegisterController.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PortfolioWebsite.BusinessLayer.Concrete;
using PortfolioWebsite.BusinessLayer.ValidationRules.FluentValidation;
using PortfolioWebsite.DataAccessLayer.EntityFramework;
using PortfolioWebsite.EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CoreDemo.Controllers
{

    public class RegisterController : Controller
    {
       WriterManager wm = new WriterManager(new EfWriterRepository());

        [HttpGet]
        public IActionResult Index()
        {
            //ViewBag.Cities = GetCityList();
            return View();
        }

        [HttpPost]
        public IActionResult Index(Writer writer, string passwordAgain, string cities)
        {
            WriterValidator wv = new WriterValidator();
            ValidationResult result = wv.Validate(writer);
            if (result.IsValid)
            {
                if (writer.WriterPassword == passwordAgain)
                {

                    writer.WriterStatus = true;
                    wm.TAdd(writer);
                    return RedirectToAction("Index", "Blog");
                }
                else
                {
                    ModelState.AddModelError("Password", "Girdiğiniz Parola Eşleşmedi, Lütfen Tekrar Deneyin");
                }
                return View();
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            return View();




           

        }
        public List<SelectListItem> GetCityList()
        {
            List<SelectListItem> list = (from x in GetCity()
                                              select new SelectListItem
                                              {
                                                  Text = x,
                                                  Value = x
                                              }).ToList();
            return list;
        }
        public List<string> GetCity()
        {
            String[] CitiesArray = new String[] { "Adana", "Adıyaman", "Afyon", "Ağrı", "Aksaray", "Amasya", "Ankara", "Antalya", "Ardahan", "Artvin", "Aydın", "Bartın", "Batman", "Balıkesir", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkari", "Hatay", "Iğdır", "Isparta", "İçel", "İstanbul", "İzmir", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kırıkkale", "Kırklareli", "Kırşehir", "Kilis", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Şırnak", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak" };
            return new List<string>(CitiesArray);
        }

    }
}

PortfolioWebsite/Views/Shared/PartialOne.cshtml
<div class="header_top" id="home">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right mx-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="index.html">
                        Anasayfa
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="about.html">Hakkımda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.html">Eğitim Bilgileri</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.html">Yayınlar ve Çalışmalar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.html">İletişim</a>
                </li>

            </ul>
            <form action="#" method="post" class="form-inline my-2 my-lg-0 header-search">
                <input class="form-control mr-sm-2" type="search" placeholder="Ara..." name="Search" required="">
                <button class="btn btn1 my-2 my-sm-0" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </form>



        </div>
    </nav>

</div>

PortfolioWebsite/Views/Shared/PartialThree.cshtml
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 footer-grid-agileits-w3ls text-left">
                <h3>Hakkımda</h3>
                <p> Şu anda aktif olarak Kocaeli Üniversitesi Elektronik ve Haberleşme Mühendisliği Bölüm Başkanı olarak görev yapmaktadır.</p>
                <div class="read">
                    <a href="single.html" class="btn btn-primary read-m">Daha Fazlasını Oku</a>
                </div>
            </div>
            <div class="col-lg-4 footer-grid-agileits-w3ls text-left">

                <div class="tech-btm">
                    <h3>Yayınlar ve Çalışmalar</h3>
                    <div class="blog-grids row mb-3">
                        <div class="col-md-5 blog-grid-left">
                            <a href="single.html">
                                <img src="~/CoreBlogTema/web/images/4.jpg" class="card-img-top img-fluid" alt="">
                            </a>
                        </div>
                        <div class="col-md-7 blog-grid-right">

                            <h5>
                                <a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
                            </h5>
                            <div class="sub-meta">
                                <span>
                                    <i class="far fa-clock"></i> 20 Jan, 2018
                                </span>
                            </div>
                        </div>

                    </div>
                    <div class="blog-grids row mb-3">
                        <div class="col-md-5 blog-grid-left">
                            <a href="single.html">
                                <img src="~/CoreBlogTema/web/images/5.jpg" class="card-img-top img-fluid" alt="">
                            </a>
                        </div>
                        <div class="col-md-7 blog-grid-right">

                            <h5>
                                <a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
                            </h5>
                            <div class="sub-meta">
                                <span>
                                    <i class="far fa-clock"></i> 20 Jan, 2018
                                </span>
                            </div>
                        </div>

                    </div>
                    <div class="blog-grids row mb-3">
                        <div class="col-md-5 blog-grid-left">
                            <a href="single.html">
                                <img src="~/CoreBlogTema/web/images/6.jpg" class="card-img-top img-fluid" alt="">
                            </a>
                        </div>
                        <div class="col-md-7 blog-grid-right">

                            <h5>
                                <a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
                            </h5>
                            <div class="sub-meta">
                                <span>
                                    <i class="far fa-clock"></i> 20 Jan, 2018
                                </span>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <!-- subscribe -->
            <div class="col-lg-4 subscribe-main footer-grid-agileits-w3ls text-left">
                <h2>Signup to our newsletter</h2>
                <div class="subscribe-main text-left">
                    <div class="subscribe-form">
                        <form action="#" method="post" class="subscribe_form">
                            <input class="form-control" type="email" placeholder="Enter your email..." required="">
                            <button type="submit" class="btn btn-primary submit">Submit</button>
                        </form>
                        <div class="clearfix"> </div>
                    </div>
                    <p>We respect your privacy.No spam ever!</p>
                </div>
                <!-- //subscribe -->
            </div>
        </div>
        <!-- footer -->
        <div class="footer-cpy text-center">
            <div class="footer-social">
                <div class="copyrighttop">
                    <ul>
                        <li class="mx-3">
                            <a class="facebook" href="#">
                                <i class="fab fa-facebook-f"></i>
                                <span>Facebook</span>
                            </a>
                        </li>
                        <li>
                            <a class="facebook" href="#">
                                <i class="fab fa-twitter"></i>
                                <span>Twitter</span>
                            </a>
                        </li>
                        <li class="mx-3">
                            <a class="facebook" href="#">
                                <i class="fab fa-google-plus-g"></i>
                                <span>Google+</span>
                            </a>
                        </li>
                        <li>
                            <a class="facebook" href="#">
                                <i class="fab fa-pinterest-p"></i>
                                <span>Pinterest</span>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
            <div class="w3layouts-agile-copyrightbottom">
                <p>
                    © @DateTime.Now.Year Prof. Dr. Ali Tangel | All Rights Reserved | Design by
                    <a href="https://www.linkedin.com/in/yusufokaraman/">Yusuf Karaman</a>
                </p>

            </div>
        </div>

        <!-- //footer -->


    </div>
</footer>

PortfolioWebsite/Views/Shared/PartialTwo.cshtml
<div class="col-md-4 top-forms text-center mt-lg-3 mt-md-1 mt-0">
    <span>Hoşgeldin _user</span>
    <span class="mx-lg-4 mx-md-2  mx-1">
        <a asp-controller="Login" asp-action="Index">
            <i class="fas fa-lock"></i> Giriş Yap
        </a>
    </span>
    <span>
        <a asp-controller="Register" asp-action="Index">
            <i class="far fa-user"></i> Kayıt Ol
        </a>
    </span>
</div>

PortfolioWebsite/Views/Shared/UserLayout.cshtml
@{
    Layout = null;
}



<!DOCTYPE html>
<html lang="tr">

<head>
    <title>Çalışma Alanı | Ali Tangel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Weblog a Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

    <script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
    </script>
    <link href="~/web/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="~/web/css/single.css">
    <link href="~/web/css/style.css" rel='stylesheet' type='text/css' />
    <link href="~/web/css/fontawesome-all.css" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800"
          rel="stylesheet">
</head>

<body>
    <!--Header-->

    <header>
        <div class="top-bar_sub_w3layouts container-fluid">
            <div class="row">
                <div class="col-md-4 logo text-left">
                    <a class="navbar-brand" href="index.html">
                        <i class="fab fa-linode"></i> Ali Tangel
                    </a>
                </div>
                @await Html.PartialAsync("PartialTwo") 
                <div class="col-md-4 log-icons text-right">

                    <ul class="social_list1 mt-3">

                        <li>
                            <a href="#" class="facebook1 mx-2">
                                <i class="fab fa-facebook-f"></i>

                            </a>
                        </li>
                        <li>
                            <a href="#" class="twitter2">
                                <i class="fab fa-twitter"></i>

                            </a>
                        </li>
                        <li>
                            <a href="#" class="dribble3 mx-2">
                                <i class="fab fa-dribbble"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="pin">
                                <i class="fab fa-pinterest-p"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        @await Html.PartialAsync("PartialOne")

    </header>
    <!--//header-->
    <!--/banner-->
    <div class="banner-inner">
    </div>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="index.html">Home</a>
        </li>
        <li class="breadcrumb-item active">Blog3</li>
    </ol>
    <!--//banner-->
    <!--/main-->
    @RenderBody()
    <!--//main-->
    <!--footer-->
    @await Html.PartialAsync("PartialThree") 
    <!---->
    <!-- js -->
    <script src="~/CoreBlogTema/web/js/jquery-2.2.3.min.js"></script>
    <!-- //js -->
    <!--/ start-smoth-scrolling -->
    <script src="~/CoreBlogTema/web/js/move-top.js"></script>
    <script src="~/CoreBlogTema/web/js/easing.js"></script>
    <script>
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 900);
			});
		});
    </script>
    <!--// end-smoth-scrolling -->

    <script>
		$(document).ready(function () {
			/*
									var defaults = {
							  			containerID: 'toTop', // fading element id
										containerHoverID: 'toTopHover', // fading element hover id
										scrollSpeed: 1200,
										easingType: 'linear'
							 		};
									*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
    </script>
    <a href="#home" class="scroll" id="toTop" style="display: block;">
        <span id="toTopHover" style="opacity: 1;"> </span>
    </a>

    <!-- //Custom-JavaScript-File-Links -->
    <script src="~/CoreBlogTema/web/js/bootstrap.js"></script>


</body>

</html>

PortfolioWebsite/Views/Shared/WriterLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <link rel="stylesheet" href="~/writer/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/writer/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/writer/assets/css/style.css">
    <link rel="shortcut icon" href="~/writer/assets/images/favicon.ico" />
</head>
<body>
    <div class="container-scroller">
        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" href="/Writer/index/"><img src="~/web/images/SMTlogo.jpg" alt="logo" /></a>
                <a class="" href="/Writer/index/"><img src="~/web/images/smallLogo.jpg" width="60" height="60" alt="logo" /></a>
            </div>
            @*<img src="~/web/images/BlogLogo.png" />*@

            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="mdi mdi-menu"></span>
                </button>
                <div class="search-field d-none d-md-block">
                    <form class="d-flex align-items-center h-100" action="#">
                        <div class="input-group">
                            <div class="input-group-prepend bg-transparent">
                                <i class="input-group-text border-0 mdi mdi-magnify"></i>
                            </div>
                            <input type="text" class="form-control bg-transparent border-0" placeholder="Ara...">
                        </div>
                    </form>
                </div>
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                            <div class="nav-profile-img">
                                <img src="~/writer/assets/images/faces/face1.jpg" alt="image">
                                <span class="availability-status online"></span>
                            </div>
                            <div class="nav-profile-text">
                                <p class="mb-1 text-black">David Greymaax</p>
                            </div>
                        </a>
                        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                            <a class="dropdown-item" href="#">
                                <i class="mdi mdi-cached mr-2 text-success"></i> Activity Log
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">
                                <i class="mdi mdi-logout mr-2 text-primary"></i> Signout
                            </a>
                        </div>
                    </li>
                    <li class="nav-item d-none d-lg-block full-screen-link">
                        <a class="nav-link">
                            <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                            <i class="mdi mdi-email-outline"></i>
                            <span class="count-symbol bg-warning"></span>
                        </a>
                        @await Component.InvokeAsync("WriterMessageNotification")
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                            <i class="mdi mdi-bell-outline"></i>
                            <span class="count-symbol bg-danger"></span>
                        </a>
                        @await Component.InvokeAsync("WriterNotifications")
                    </li>
                    <li class="nav-item nav-logout d-none d-lg-block">
                        <a class="nav-link" href="#">
                            <i class="mdi mdi-power"></i>
                        </a>
                    </li>
                    <li class="nav-item nav-settings d-none d-lg-block">
                        <a class="nav-link" href="#">
                            <i class="mdi mdi-format-line-spacing"></i>
                        </a>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>

        <div class="container-fluid page-body-wrapper">

            @await Html.PartialAsync("~/Views/Writer/WriterNavbarPartial.cshtml")

            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>

                @await Html.PartialAsync("~/Views/Writer/WriterFooterPartial.cshtml")

            </div>

        </div>

    </div>

    <script src="~/writer/assets/vendors/js/vendor.bundle.base.js"></script>
    <script src="~/writer/assets/js/off-canvas.js"></script>
    <script src="~/writer/assets/js/hoverable-collapse.js"></script>
    <script src="~/writer/assets/js/misc.js"></script>
    


</body>
</html>